from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_AVVA(object):
    def setupUi(self, AVVA):
        AVVA.setObjectName("AVVA")
        AVVA.resize(1379, 683)
        self.centralwidget = QtWidgets.QWidget(AVVA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -30, 1401, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1100, 500, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(106, 255, 103);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1210, 500, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 7, 52);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-120, 300, 471, 301))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("gif3.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 580, 211, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, -40, 551, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("gif 1.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(820, 60, 191, 41))
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n" 
"border-radius:none;\n"
"color:black;\n"                                       
"spin_box.setButonSymbols(2);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1120, 60, 181, 41))
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"spin_box.setButonSymbols(2);")

        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 580, 1391, 101))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("small.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 300, 181, 281))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("new.gif"))
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(770, 30, 301, 101))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("images.jpeg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1070, 30, 291, 101))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("images.jpeg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        AVVA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AVVA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1379, 21))
        self.menubar.setObjectName("menubar")
        AVVA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AVVA)
        self.statusbar.setObjectName("statusbar")
        AVVA.setStatusBar(self.statusbar)

        self.retranslateUi(AVVA)
        QtCore.QMetaObject.connectSlotsByName(AVVA)

    def retranslateUi(self, AVVA):
        _translate = QtCore.QCoreApplication.translate
        AVVA.setWindowTitle(_translate("AVVA", "MainWindow"))
        self.pushButton.setText(_translate("AVVA", "Run"))
        self.pushButton_2.setText(_translate("AVVA", "Exit"))
        self.label_3.setText(_translate("AVVA", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AVVA = QtWidgets.QMainWindow()
    ui = Ui_AVVA()
    ui.setupUi(AVVA)
    AVVA.show()
    sys.exit(app.exec_())
